### ISSUE TITLE
Database column names in templates

### ISSUE THREAD

**Issue by klimesf** [klimesf/notejam#1]
I decided to use vanilla Nette in this app, that means I went with Nette\Database instead of Doctrine, which I am used to.

I define column names in `app/model` classes ([example](https://github.com/klimesf/notejam/blob/master/nette/notejam/app/model/NoteManager.php#L21)), however, I need to access these columns in templates ([example](https://github.com/klimesf/notejam/blob/master/nette/notejam/app/presenters/templates/Note/default.latte#L4)) aswell.

Is there any best practise for this? Shall I use the constans of model class, or just access those columns directly and hope I won't forget to fix this, when schema changes?

**Comment by hrach** [comment]
just access those columns directly

**Comment by Tharos** [comment]
Or you can use Schematic ;). https://github.com/Tharos/Schematic

```php
// Presenter
$this->template->note = EntryViewer::viewEntry($note, function (Row $note) {
	return [
		'id' => $note->id,
		'name' => $note->name,
		'updated_at' => $note->updated_at,
	];
});
```

You don't have to change anything in your template.

Schematic is extremely lightweight library I use when handling data without schema (JSON-decoded data from remote APIs, data fetched from Redis, array-hydrated data by Doctrine…). It helps me to rename and find all usages of such columns with one click in PhpStorm.

I've published it two days ago a I'd like to write some basic documentation about it soon. :)

**Comment by Tharos** [comment]
In short, Schematic solves two issues. It allows you to define schema of array-based data so that IDE understand it (via `@property` annotation) and it provides simple view object for loosing coupling between model and (typically) Latte templates.

**Comment by klimesf** [comment]
@hrach & @Tharos thank you, guys :)

@Tharos: hmm, that looks nice, I will look into it!
